<a href="https://colab.research.google.com/github/Ayushman0Singh/CardiovascularDiseaseRiskPrediction/blob/main/CardiovascularRiskPrediction(ModelTesting).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns

In [104]:
file_path = '/content/drive/MyDrive/Almabetter/Capstone Projects/Supervised ML-Classification /Copy of data_cardiovascular_risk.csv'
df = pd.read_csv(file_path)

In [105]:
df.head(5)

id  age  education sex is_smoking  cigsPerDay  BPMeds  prevalentStroke  \
0   0   64        2.0   F        YES         3.0     0.0                0   
1   1   36        4.0   M         NO         0.0     0.0                0   
2   2   46        1.0   F        YES        10.0     0.0                0   
3   3   50        1.0   M        YES        20.0     0.0                0   
4   4   64        1.0   F        YES        30.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    221.0  148.0   85.0    NaN       90.0     80.0   
1             1         0    212.0  168.0   98.0  29.77       72.0     75.0   
2             0         0    250.0  116.0   71.0  20.35       88.0     94.0   
3             1         0    233.0  158.0   88.0  28.26       68.0     94.0   
4             0         0    241.0  136.5   85.0  26.42       70.0     77.0   

   TenYearCHD  
0           1  
1           0  
2           0  
3           1  
4           0

In [106]:
df.shape

(3390, 17)

In [107]:
df.isnull().sum()

id                   0
age                  0
education           87
sex                  0
is_smoking           0
cigsPerDay          22
BPMeds              44
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             38
sysBP                0
diaBP                0
BMI                 14
heartRate            1
glucose            304
TenYearCHD           0
dtype: int64

In [108]:
df = df.dropna(how ='any')

In [109]:
#prevalance in the data set
df['TenYearCHD'].value_counts(normalize=True)

0    0.848309
1    0.151691
Name: TenYearCHD, dtype: float64

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2927 entries, 1 to 3389
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               2927 non-null   int64  
 1   age              2927 non-null   int64  
 2   education        2927 non-null   float64
 3   sex              2927 non-null   object 
 4   is_smoking       2927 non-null   object 
 5   cigsPerDay       2927 non-null   float64
 6   BPMeds           2927 non-null   float64
 7   prevalentStroke  2927 non-null   int64  
 8   prevalentHyp     2927 non-null   int64  
 9   diabetes         2927 non-null   int64  
 10  totChol          2927 non-null   float64
 11  sysBP            2927 non-null   float64
 12  diaBP            2927 non-null   float64
 13  BMI              2927 non-null   float64
 14  heartRate        2927 non-null   float64
 15  glucose          2927 non-null   float64
 16  TenYearCHD       2927 non-null   int64  
dtypes: float64(9),

In [111]:
df.drop(labels = 'education', axis = 1, inplace = True)

In [112]:
features = list(df.columns)[1:-1]
X = df[features]
y = df['TenYearCHD']
X = pd.get_dummies(X,columns=['sex', 'is_smoking', 'prevalentStroke', 'prevalentHyp', 'diabetes'])
X.sample(5)

age  cigsPerDay  BPMeds  totChol  sysBP  diaBP    BMI  heartRate  \
2379   40         0.0     0.0    267.0  150.0   93.0  31.77       93.0   
2      46        10.0     0.0    250.0  116.0   71.0  20.35       88.0   
1495   55        20.0     0.0    280.0  134.0   85.5  29.86       80.0   
2388   42         0.0     0.0    253.0  116.0   72.0  21.96       60.0   
1795   45        20.0     0.0    218.0  130.0   87.0  24.10       72.0   

      glucose  sex_F  sex_M  is_smoking_NO  is_smoking_YES  prevalentStroke_0  \
2379     74.0      1      0              1               0                  1   
2        94.0      1      0              0               1                  1   
1495     75.0      0      1              0               1                  1   
2388     88.0      0      1              1               0                  1   
1795     64.0      0      1              0               1                  1   

      prevalentStroke_1  prevalentHyp_0  prevalentHyp_1  diabetes_0  \
2379                  0               1               0           1   
2                     0               1               0           1   
1495                  0               1               0           1   
2388                  0               1               0           1   
1795                  0               1               0           1   

      diabetes_1  
2379           0  
2              0  
1495           0  
2388           0  
1795           0

In [116]:
 #test-train split
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split( X,y , test_size = 0.15, stratify= y , random_state = 42) 
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2487, 19)
(440, 19)
(2487,)
(440,)


In [117]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix

# Decision Trees

In [125]:
#Decision tree Classifier Hyperparameter tunning
DT= DecisionTreeClassifier()
DT_param = {'max_depth':np.arange(10,40,2), 'max_leaf_nodes':np.arange(50,150,10)}
DT = GridSearchCV(DT, param_grid= DT_param, scoring ='f1' , cv = 5)
DT.fit(X_train,y_train)
print(DT.best_params_)
DT = DT.best_estimator_

{'max_depth': 36, 'max_leaf_nodes': 140}


In [126]:
y_pred_test_DT = DT.predict(X_test)
y_pred_train_DT = DT.predict(X_train)
print('f1 score on test set:', f1_score(y_test,y_pred_test_DT))
print('f1 score on train set:',f1_score(y_train,y_pred_train_DT) )
print('Auc_score Test:', roc_auc_score(y_test,y_pred_test_DT))
print('Auc_score Train:', roc_auc_score(y_train,y_pred_train_DT))
# Recall is an important metric in this case
print('Recall Score:', recall_score(y_test,y_pred_test_DT))
# Since its binary classiffication, lets check the confusion matrix
print('\nConfusion matrix\n', confusion_matrix(y_test,y_pred_test_DT,labels=[1,0]))
print('Confusion matrix train\n', confusion_matrix(y_train,y_pred_train_DT,labels=[1,0]))
print('Confusion matrix model\n', confusion_matrix(y_test,y_pred_test_DT,labels=[1,0]) + confusion_matrix(y_train,y_pred_train_DT,labels=[1,0]))

f1 score on test set: 0.14141414141414144
f1 score on train set: 0.7463651050080775
Auc_score Test: 0.5187267416269857
Auc_score Train: 0.803759412674268
Recall Score: 0.1044776119402985

Confusion matrix
 [[  7  60]
 [ 25 348]]
Confusion matrix train
 [[ 231  146]
 [  11 2099]]
Confusion matrix model
 [[ 238  206]
 [  36 2447]]


# Random forest

In [120]:
# RF hyper parameter tunnig
rf = RandomForestClassifier()
rf_params = {'n_estimators':[150,250,350], }